#!/bin/bash
# ==========================================================================
#  readme    : repo utiliies
#  mail      : joongkeun.kim@lge.com, av9300@gmail.com
# ==========================================================================
##---------------------------------------------------------- DEBUG OPTION
#DEBUG=["echo -e"|:], : means no-operation
DEBUG=:
SCRIPT_DIR=${BASH_SOURCE%/*}

source ${SCRIPT_DIR}/prelibrary
#user setting
account=vc.integrator
mirror="/data001/${account}"/mirror
file_error=~/.repoconfig/repo.error
path_mirror=/data001/vc.integrator/mirror
rm -f ${file_error}


##--------------------------- Menu Functions --------------------------------
##============================================================================

function getGitRootPath(){ 
## ---------------------------------------------------------------------------
# get repo dir path from repo sub directory
    echo $(git rev-parse --show-toplevel);
}



function runSSHcheckError(){ 
## ---------------------------------------------------------------------------
# run command, get return code and print guide
    echo "\$ $@" ;"$@" 
    case $? in
     0) ;;
     1) echo Generic error, usually because invalid command line options or malformed configuration;;
     2) echo Connection failed;;
    65) echo Host not allowed to connect;;
    66) echo General error in ssh protocol;;
    67) echo Key exchange failed;;
    68) echo Reserved;;
    69) echo MAC error;;
    70) echo Compression error;;
    71) echo Service not available;;
    72) echo Protocol version not supported;;
    73) echo Host key not verifiable;;
    74) echo Connection failed;;
    75) echo Disconnected by application;;
    76) echo Too many connections;;
    77) echo Authentication cancelled by user;;
    78) echo No more authentication methods available;;
    79) echo Invalid user name;;
     *) echo Unknown Error;;
    esac
}



function runRepoInitcheckError(){ 
## ---------------------------------------------------------------------------
# run command, get return code and print guide
    echo "\$ $@"  
    "$@" 2> >(tee -a ${file_error})
    #"$@" | tee -a ${file_error}
    case $? in
     0) ;;
     1) echo Generic error, usually because invalid command line options or malformed configuration;;
     2) echo Connection failed;;
    esac
}
 
 
 
function runRepoSynccheckError(){ 
## ---------------------------------------------------------------------------
# run command, get return code and print guide
# ex) runRepoSynccheckError --depth=1 32
    if [ -z "$2" ]; then read -p "Please input job number to repo sync [enter:auto| number:ex)16| ctrl+c:exit]: " njobs; fi
    if [ -z $njobs ]; then  njobs=$(( $(nproc --all) / 4)); fi
    showRUN repo sync -qcj${njobs:-16} --no-tags --no-clone-bundle $1

    #"$@" 2> >(tee -a ${file_error})
    "$@" > >(tee -a ${file_error})
    case $? in
     0) ;;
     1) echo Generic error, usually because invalid command line options or malformed configuration;;
     2) echo Connection failed;;
     *) echo Unknown Error;;
    esac
}
 
 
 
function findFileLocation(){
## ---------------------------------------------------------------------------
## find input-path up and down, 
## $1:path name, $2:max depth to sub dir
## ex) findFileLocation .repo 5
## ex) findFileLocation .git 2

    local target=${1:-.repo}
    local down_depth=${2:-2} #default value:2
    local ret=()
    
    # find in sub directory with depth
    readarray -t ret < <(find . -maxdepth ${down_depth} -path "*${target}")
    case ${#ret[@]} in
    1)  # already found sub dir
        REPO_PATH=$(readlink -f ${ret[0]})
        ;;
    0)  # find in parent directory upto $HOME
        while [[ "${PWD}" =~ "${HOME}" ]]; do
            if [ -d ${target} ]; then break; fi
            cd ..
        done
        if [ -d ${target} ]; then REPO_PATH=$(readlink -f ${target});else REPO_PATH="NULL";fi
        ;;
    *)  # found multiple dir in sub dir
        printf "subdir [%s]\n" ${#ret[@]}
        printf "%s\n" ${ret[@]}; 
        REPO_PATH="NULL"
        ;;
    esac
    #if [ "$1" = "show" ];then 
        bar inline "repo path"
        log "${REPO_PATH}"
    #fi
}



function getRepoCMD(){
## ---------------------------------------------------------------------------
# get repo command from exising repo project
# $1 show repo command (default: save info to each variable such as REMOTE_URL, BRANCH_REPO, ...)
    findFileLocation .repo/manifests 5
    if [ -d "${REPO_PATH}" ];then cd ${REPO_PATH};else error "you are not in repo project";exit;fi
    
    local count file_tempa file_tempb 
        
    #set global variable
    REMOTE_URL=$(git remote -v |grep fetch |awk '{print $2}')
    BRANCH_REPO=$(git rev-parse --abbrev-ref --symbolic-full-name @{u}| sed 's:.*/::')
    REPO_URL=$(cat ../repo/.git/config |grep url|sed 's/.*=\(.*\)/\1/')
    REFER_MIRROR=$(cat ../manifests.git/config |grep reference|sed 's/.*=\(.*\)/\1/')

    if [ -z "${BRANCH_REPO}" ]; then 
        printf "${RED}[warning] please check if you have switched to a topic branch from after repo init${NCOL}\n"
        printf "${RED}[warning] temporarily set to local branch name${NCOL}\n"
        printf "\tyou can set-up upstream branch with: git branch -u %s <branch-name>\n" "$(echo $(git remote -v |cut -f1))"
        BRANCH_REPO=$(git rev-parse --abbrev-ref HEAD)
    fi
    
    # find using manifest.xml
    file_tempa=$(ls -Art ../*.xml | tail -n 1)
    count=$(grep -c include ${file_tempa})
    if [ -L "${file_tempa}" ];then 
        file_tempb=$(readlink "${file_tempa}")
        FILE_MANI=${file_tempb#*/}
    elif [ $count -eq 1 ]; then
        FILE_MANI=$(grep include $file_tempa |sed -E 's/<.*name="(.*)".\/>/\1/')
    else
        FILE_MANI=default.xml
    fi

    if [ -n "$REFER_MIRROR" ];then EXTRA_OPTION="--reference $REFER_MIRROR"; fi
    if [ "$1" = "show" ];then 
        bar inline "repo-init cmd"
        log "repo init -u $REMOTE_URL -b $BRANCH_REPO -m $FILE_MANI --repo-url $REPO_URL $EXTRA_OPTION"
    fi
    return 0
}



function findProperREPLServer(){
## ---------------------------------------------------------------------------
# find replication server 
# $1 log-file to show result
    local server_PORT=29418
    local server_URL=( lampmg1.lge.com lampgd1.lge.com )
    local file_temp=$(mktemp)
    local system_load=( 0 0 )
    local min_load=10000 
    local i=0
    local get_delay get_connection get_task get_mem 
    local printformat="%-20s|%10s|%14s|%10s|%12s|%10s"
    
    printf "replication server from lamp.lge.com: \n" >> $1
    printf "${printformat}\n" "server list" "delay(ms)" "connections(#)" "tasks(#)" "free memory" "total load" >> $1
    printf "${yellow}--------------------------------------------------------------------------------------\n${NCOL}" >> $1
    for server in "${server_URL[@]}"; do
        get_delay=$(ping ${server} -s 1016 -c 4 -A |sed -ne 's/.*ewma.*\/\(.*\) ms$/\1/p' | sed 's/\.//')
        if [ $? -ne 0 ]; then continue; fi 
        
        ssh -p ${server_PORT} -o ConnectTimeout=2 -o ConnectionAttempts=1 \
            ${server} gerrit show-caches | grep -E "(^SSH:|^Tasks:|^Mem:)" > ${file_temp}
        if [ $? -ne 0 ]; then continue;fi 

        get_connection=$(sed -n 's/^SSH: *\(.*\) users.*/\1/p' ${file_temp})
        get_task=$(sed -n 's/^Tasks: *\(.*\) total.*/\1/p' ${file_temp})
        get_mem=$(sed -n 's/^Mem:.*+ \(.*\) free.*/\1/p' ${file_temp})
        system_load[i]=$(echo "$get_delay/10 + $get_connection*80 + $get_task*100 + ${system_load[i]}" |bc )

        printf "${printformat}\n" $server $get_delay $get_connection $get_task $get_mem ${system_load[i]} >> $1
        if (( "${min_load}" >= "${system_load[i]}" )); then min_load=$system_load; REPL_SERVER="$server:$server_PORT"; fi
        (( i++ ))
    done

    rm -f ${file_temp}
}



function repoInit(){
## ---------------------------------------------------------------------------
# repo init helper
# $1 short repo init command
    #option handle
    local url revision manifest platform reference depth repo_url extra
    if ! options=$(getopt -l reference:,depth:,repo-url:,no-clone-bundle,partial-clone,no-tags,mirror -o b:m:p:u: -- "$@")
    then error 'please check "repo init --help"'; exit 1; fi

    #reset legacy positional parameter except $options
    eval set -- "$options"
    while true; do
        case $1 in
            #when option has sub option, should shift 2 or just shift
            -u|--manifest-url)                                          url=$2;         shift 2;;
            -b|--manifest-branch)                                       revision=$2;    shift 2;;
            -m|--manifest-name)                                         manifest=$2;    shift 2;;
            -p|--platform)                                              platform=$2;    shift 2;;
            --reference)                                                reference=$2;   shift 2;;
            --depth)                                                    depth=$2;       shift 2;;
            --repo-url)                                                 repo_url=$2;    shift 2;;
            #single option that need no additional sub value          
            #skip single option and remove getopt cmd                 
            -c|--current-branch)                                  extra="${extra} $1";  shift 1;;
            --no-clone-bundle|--partial-clone|--no-tags|--mirror) extra="${extra} $1";  shift 1;;
            --|*)                                                                  shift; break;;
        esac
    done

    #revision handle
    if [ -z "${revision}" ];then
        printf "usage: vrepo init -b [branch] [-m manifest.xml] \n";
        bar outline         
        printf "ex: vrepo init -b lampauto_s_release -m all.xml \n";
        printf "ex: vrepo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
        printf "ex: vrepo init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
        exit
    fi

    #url handle with replication server
    local file_info=$(mktemp)
    bar outline 'repo server info' > ${file_info}
    findProperREPLServer ${file_info}
    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then url="ssh://${REPL_SERVER}/platform/manifest.git"; fi
    if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
    if [ -z "${repo_url}" ] || [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29418/repo/git-repo.git';fi;

    cmd_repoinit="repo init ${url:+-u ${url}} ${revision:+-b ${revision}} ${manifest:+-m ${manifest}} ${platform:+-p ${platform}} ${reference:+--reference=${reference}} ${depth:+--depth=${depth}} ${repo_url:+--repo-url=${repo_url}} ${extra} $@"

    #make final repo init cmd
    bar outline "generated full command:\n" >> ${file_info}
    printf "${cmd_repoinit}" >> ${file_info}
    
    #execute cmd
    time runRepoInitcheckError ${cmd_repoinit}
    bar outline >> ${file_info}
    printf "${red}error logfile: ${file_error} ${NCOL}\n" >> ${file_info}
    bar outline >> ${file_info}
    
    #show repo info
    cat ${file_info}; rm -f ${file_info}
    return
}

function repoInit_(){
## ---------------------------------------------------------------------------
# repo init helper
# $1 short repo init command
    #option handle
    local repo_URL url_repl url revision manifest opt left
    while getopts m:b:u:c opt 2> /dev/null; do
       case $opt in
          u) url=$OPTARG;;
          b) revision=$OPTARG;;
          m) manifest=$OPTARG
            read -p [$manifest]
          ;; 
          c) current=$OPTARG;;
          *) left=${left} $OPTARG;;
       esac
    done

    #revision handle
    if [ -z "${revision}" ]; then 
        printf "usage: vrepo init -b [branch] [-m manifest.xml] \n";
        bar outline         
        printf "ex: vrepo init -b lampauto_s_release -m all.xml \n";
        printf "ex: vrepo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
        printf "ex: vrepo init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
        echo "${revision}"
        exit
    fi
    
    local path_mirror='--reference=/data001/vc.integrator/mirror'
    local url_mirror=${path_mirror}/${revision}

    #url handle with replication server
    local file_info=$(mktemp)
    bar outline 'repo server info' > ${file_info}
    findProperREPLServer ${file_info}
    
    
    local cmd_repoinit="repo init $@ ${url_mirror}"
    if [ -z "${url}" ];               then cmd_repoinit="${cmd_repoinit} -u ssh://${REPL_SERVER}/platform/manifest.git"; fi
    if [[ "${revision}" =~ "lamp" ]]; then 
        cmd_repoinit="${cmd_repoinit} --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git"; 
    else 
        cmd_repoinit="${cmd_repoinit}"; 
    fi

    if [ -n "${current}" ];           then cmd_repoinit="${cmd_repoinit} -c ${current}"  ;fi    

    #make final repo init cmd
    bar outline >> ${file_info}
    printf "generated full command:\n" >> ${file_info}
    printf "${cmd_repoinit}\n" >> ${file_info}
    
    #execute cmd
    time runRepoInitcheckError ${cmd_repoinit}
    bar outline >> ${file_info}
    printf "${red}error logfile: ${file_error} ${NCOL}\n" >> ${file_info}
    bar outline >> ${file_info}
    
    #show repo info
    cat ${file_info}; rm -f ${file_info}
    return
}

function repoInit__(){
## ---------------------------------------------------------------------------
# repo init helper
# $1 short repo init command
    if ! options=$(getopt -o u:b:m:cp: -l repo-url:,mirror:,reference:,depth:,no-tags,no-clone-bundle,partial-clone -- "$@")
    then
        echo "ERROR: print usage"
        exit 1
    fi

    #reset legacy positional parameter except $options
    eval set -- $options
    while true; do
        case "$1" in
            -u|--manifest-url) 
                echo >&2 "$1 was triggered!, OPTARG: $2"
                shift 2;;
            -b|--manifest-branch)    
                echo >&2 "$1 was triggered!, OPTARG: $2"
                shift 2;; #when option has sub param, should shift 2
            -m|--manifest-name)
                echo >&2 "$1 was triggered!, OPTARG: $2"
                shift 2;;
            -c|--current-branch)
                echo >&2 "$1 was triggered!, OPTARG: $2"
                shift ;; 
            --mirror|--reference|--depth|--repo-url)
                echo >&2 "$1 was triggered!, OPTARG: $2"
                shift 2;;
            --no-clone-bundle|--partial-clone|--no-tags)
                echo >&2 "$1 was triggered!"
                shift;;
            --)           
                shift 
                break ;;
            *)           
                shift 
                break ;;               
        esac
    done

    echo -------------------- leftover
    echo "$@"

    exit
}





function showManifestFile(){
## ---------------------------------------------------------------------------
# read file and print line "include" keyword
# $1 manifest file name
# $2 treedepth to display sub manifest
    local file 
    local path='|--|--|--|--|--'
    local treedepth=${2:-0}

    (( treedepth=treedepth+3 ))
    cat $1 | sed -n 's/.*include name="\(.*\)".*/\1/p' | while read -r file; do
        if [ -n "${file}" ];then   
            printf "%s${file} %s\n" "${path::${treedepth}}"
            showManifestFile ${file} ${treedepth}
        fi
        
    done
    (( treedepth=treedepth-3 ))
}

 

function getRepoInfo(){
## ---------------------------------------------------------------------------
# print information of repo
# $1 manifests file (default is current manifests)

    oldIFS=${IFS}; IFS=''; 
    getRepoCMD show
    
    local manifest=${1:-${FILE_MANI}}
    bar inline "manifests: ${manifest}"
    showManifestFile ${manifest}
    
    IFS=${oldIFS}
}



function handleMenu(){
## ---------------------------------------------------------------------------
# show ui menu for this script
printf ${green}
cat << PREFACE
==============================================================
 the menu for repo tools
 -------------------------------------------------------------
 supported command: ex) vrepo info
     info) info
     download) init sync auto
==============================================================
PREFACE
printf ${NCOL}

    local COLUMNS=60
    PS3=$'\e[00;35m=== Please input command! [enter:menu, number:choice, ctrl+c:exit] === : \e[0m'
    select CHOICE in info init sync 
    do
        handleCommand $CHOICE
    done
}


 
function handleCommand(){
## ---------------------------------------------------------------------------
# main handler for this script
# $1 command

local ret=0
    case $1 in
        init) repoInit "${@:2}"
            printf "${YELLOW}To RUN next command: ${NCOL}\n"
            runRepoSynccheckError                       ;;
        sync) runRepoSynccheckError                     ;;
        info) getRepoInfo
              bar inline "repo info"
              repo info                                 ;;
        "") handleMenu "${@}"                           ;;
        *) repo "${@}"
          return $ret                                   ;;
    esac
}



##============================================================================
## Main
##============================================================================
#set -x
handleCommand $@
if [ $? -ne 0 ];then echo "needto add function"; fi
