#!/bin/bash
# ==========================================================================
#  readme    : repo utiliies
#  mail      : joongkeun.kim@lge.com, av9300@gmail.com
# ==========================================================================
##---------------------------------------------------------- DEBUG OPTION
#DEBUG=["echo -e"|:], : means no-operation
DEBUG=:
PATH_FULL=$(realpath "$BASH_SOURCE")
PATH_DIR="${PATH_FULL%/*}"
PATH_FILE="${PATH_FULL##*/}"
DIR_CURR=$(pwd)
LC_ALL=C.UTF-8

#suppress print path
pushd() { command pushd "$@" > /dev/null ;}
popd() { command popd "$@" > /dev/null ;}
NJOBS=$(( $(nproc --all) / 4))

$DEBUG "[$_][$BASH_SOURCE][$0]  [${PATH_FULL}][${PATH_DIR}][${PATH_FILE}]"

if [ -e "${PATH_DIR}/prelibrary" ]; then source ${PATH_DIR}/prelibrary;
else source ${proFILEdir}/tools/prelibrary; fi
#user setting
account=vc.integrator
path_mirror="/data001/${account}"/mirror


##--------------------------- Menu Functions --------------------------------
##============================================================================

function reppcheck_gerritconnection(){
## ---------------------------------------------------------------------------
# run command, get return code and print guide
    echo "\$ $@" ;"$@"

    case $? in
     0) ;;
     1) echo Generic error, usually because invalid command line options or malformed configuration;;
     *) echo Gerrit Connection Error;;
    esac
}



function reppcheck_sshconnection(){
## ---------------------------------------------------------------------------
# run command, get return code and print guide
    local file_error=$(mktemp)
    echo "\$ ssh -T $1 -p $2" ;
    echo . | ssh -T $1 -p $2 2> ${file_error}

    case $(cat $file_error) in
     *success*) echo good, it works;;
     *publickey*) echo check publickey;;
     *) echo unknown error is occured;;
    esac

    #rm -f ${file_error}
}



function reppfind_initerror(){
## ---------------------------------------------------------------------------
# run command, get return code and print guide
    local file_error=$(mktemp)
    local ret=1 #return 1 is success, 0 is fail
    echo "\$ $@"
    time "$@" 2> >(tee -a ${file_error})
    #"$@" | tee -a ${file_error}

    grep -nEe "(fatal|fail|error)" ${file_error} >/dev/null
    if [ $? -eq 0 ]; then
        bar outline "check error"
        err "${file_error}"
        ret=0
    fi

    grep 'Permission denied (publickey)' ${file_error} >/dev/null
    if [ $? -eq 0 ]; then
        err "http://collab.lge.com/main/display/SWIFR/repo#publickey"
        ret=0
    fi

    #if [ $? -ne 0 ];then reppcheck_sshconnection ssh -p vc.integrator@vgit.lge.com:29430;fi

    return $ret
}



function reppfind_syncerror(){
## ---------------------------------------------------------------------------
# run command, get return code and print guide
# ex) reppfind_syncerror
    if [ -z "$1" ]; then
        read -p "Please input job number to repo sync [enter:auto| number:ex)16| ctrl+c:exit]: " njobs;
        if [ -z $njobs ]; then  njobs=${NJOBS}; fi
    else
        njobs=$1
    fi

    showRUN repo sync --no-tags --no-clone-bundle --fail-fast -qcj${njobs:-16} $2

    #"$@" 2> >(tee -a ${file_error})
    "$@" > >(tee -a ${file_error})
    case $? in
     0) ;;
     1) echo Generic error, usually because invalid command line options or malformed configuration;;
     2) echo Connection failed;;
     *) echo Unknown Error;;
    esac
}



function reppfind_repodir(){
## ---------------------------------------------------------------------------
## find input-path up and down,
## $1:path name, $2:max depth to sub dir, $3:print or not
## ex) reppfind_repodir .repo 5
## ex) reppfind_repodir .git 2
    local T=$PWD
    local target=${1:-.repo}
    local down_depth=${2:-2} #default value:2
    local print=$3

    # find in sub directory with depth
    readarray -t REPP_PATH_ALL < <(find . -maxdepth ${down_depth} -path "*${target}" |sort)
    case ${#REPP_PATH_ALL[@]} in
    1)  # found sub dir
        REPP_PATH=$(readlink -f ${REPP_PATH_ALL[0]})
        ;;
    0)  # not found, so find in parent directory upto $HOME
        while [[ "${PWD}" =~ "${HOME}" ]]; do
            if [ -d ${target} ]; then break; fi
            pushd ..
        done
        if [ -d ${target} ]; then REPP_PATH=$(readlink -f ${target});else REPP_PATH='';fi
        pushd -0 && dirs -c
        cd $T
        ;;
    *)  # found multiple dir in sub dir
        if [ "$print" = "print_y" ]; then
            printf "subdir [%s]\n" ${#REPP_PATH_ALL[@]}
            printf "%s\n" ${REPP_PATH_ALL[@]};
        fi
        REPP_PATH=''
        ;;
    esac
}



function reppget_repcmd(){
## ---------------------------------------------------------------------------
# get repo command from exising repo project
# $1 show repo command (default: save info to each variable such as REPP_REMOTE, REPP_BRANCH, ...)
    local count file_tempa file_tempb

    if [ -z "${REPP_BRANCH}" ]; then
        printf "${RED}[warning] please check if you have switched to a topic branch from after repo init${NCOL}\n"
        printf "${RED}[warning] temporarily set to local branch name${NCOL}\n"
        printf "\tyou can set-up upstream branch with: git branch -u %s <branch-name>\n" "$(echo $(git remote -v |cut -f1))"
        REPP_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    fi

    # find using manifest.xml
    file_tempa=$(command ls -Art ../*.xml | tail -n 1)
    count=$(grep -c include ${file_tempa})
    if [ -L "${file_tempa}" ];then
        file_tempb=$(readlink "${file_tempa}")
        FILE_MANI=${file_tempb#*/}
    elif [ $count -eq 1 ]; then
        file_tempb=$(grep include $file_tempa |sed -E 's/<.*name="(.*)".\/>/\1/')
        FILE_MANI=${file_tempb// /}
    else
        FILE_MANI=default.xml
    fi

    if [ -n "$REPP_MIRROR" ];then EXTRA_OPTION="--reference=$REPP_MIRROR"; fi
    if [ "$1" = "info" ];then
        bar inline "repo-init cmd"
        REPP_CMD="repo init -u $REPP_REMOTE -b $REPP_BRANCH -m $FILE_MANI --repo-url=$REPP_URL $EXTRA_OPTION"
        log "${REPP_CMD}"
    fi
    return 0
}



function reppgo() {
## ---------------------------------------------------------------------------
# return git root path or return near git path
    local T=$(pwd)
    if [ "${REPP_ROOT}" = "${T}" ]; then 
        echo "your are in repo root, use 'repp find @path' to list up all repositories" && return 0; 
    fi
    
    #find path to upper dirs until HOME or ROOT.
    dirs -c
    while [ "$T" != "$HOME" ] && [ "$T" != "/"  ]; do
        T=$PWD
        if [ -d "$T/$1" ]; then cd $T && return 0; fi
        pushd .. > /dev/null
    done
    
    #not found in partents, now findout in child
    pushd -0 && dirs -c > /dev/null
    #echo "no .git found, stay HERE"

    local INPUT=( $(find ../.. -maxdepth 4 -name "$1" 2> /dev/null |head -60))
    #local INPUT=( $(reppfind @path) )

    if [ -n "${INPUT}" ];then run_menu "${INPUT[@]}" ;  fi
    cd "${menu_selected}/.."
}



function reppinit(){
## ---------------------------------------------------------------------------
# repo init helper
# $1 short repo init command
    #option handle
    local url revision manifest platform reference depth repo_url extra ret=0
    if ! options=$(getopt -l reference:,depth:,repo-url:,no-clone-bundle,partial-clone,no-tags,mirror -o b:m:p:u: -- "$@")
    then err 'please check "repo init --help"'; exit 1; fi

    if [ -z $1 ]; then printElement 'please refer http://collab.lge.com/main/x/wY6wa' && exit 1;fi

    #reset legacy positional parameter except $options
    eval set -- "$options"
    while true; do
        case $1 in
            #when option has sub option, should shift 2 or just shift
            -u|--manifest-url)                                          url=$2;         shift 2;;
            -b|--manifest-branch)                                       revision=$2;    shift 2;;
            -m|--manifest-name)                                         manifest=$2;    shift 2;;
            -p|--platform)                                              platform=$2;    shift 2;;
            --reference)                                                reference=$2;   shift 2;;
            --depth)                                                    depth=$2;       shift 2;;
            --repo-url)                                                 repo_url=$2;    shift 2;;
            #single option that need no additional sub value
            #skip single option and remove getopt cmd
            -c|--current-branch)                                  extra="${extra} $1";  shift 1;;
            --no-clone-bundle|--partial-clone|--no-tags|--mirror) extra="${extra} $1";  shift 1;;
            --|*)                                                                  shift; break;;
        esac
    done

    #revision handle, if url has lamp
    if [ -z "${revision}" ] && [ "${url}" != "${url/lamp/}" ]; then
        printf "usage: repp init -b [branch] [-m manifest.xml] \n";
        bar outline
        printf "ex: repp init -b lampauto_s_release -m all.xml \n";
        printf "ex: repp init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
        printf "ex: repp init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
        exit
    fi

    #url handle with replication server
    local file_info=$(mktemp)
    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then
        url="ssh://lamp.lge.com:29418/platform/manifest.git";
        printf "-u option is necessary";
        printf "usage: repp init -u ssh://${USER}@vgit.lge.com:29440\n ~~~ ";
    fi
    if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
    if [ -z "${repo_url}" ] && [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29418/repo/git-repo.git';fi;

    cmd_repoinit="repo init ${url:+-u ${url}} ${revision:+-b ${revision}} ${manifest:+-m ${manifest}} ${platform:+-p ${platform}} ${reference:+--reference=${reference}} ${depth:+--depth=${depth}} ${repo_url:+--repo-url=${repo_url}} ${extra} $@"

    #make final repo init cmd
    bar outline "executed command:" >> ${file_info}
    printf "${cmd_repoinit}\n" >> ${file_info}

    #execute cmd
    if reppfind_initerror ${cmd_repoinit}; then ret=1; fi

    #show repo info
    bar outline >> ${file_info}
    cat ${file_info}; rm -f ${file_info}

    return $ret
}



function reppshow_manifesttree(){
## ---------------------------------------------------------------------------
# read file and print line "include" keyword
# $1 manifest file name
# $2 treedepth to display sub manifest
    local file
    local path='|--|--|--|--|--|--'
    local treedepth=${2:-0}
    listxml=()

    #print name of manifest
    listxml+=($1) 
    printf "%s$1 \n" "${path::${treedepth}}"

    (( treedepth=treedepth+3 ))
    #print name of branches
    cat $1| sed -n 's/.*revision="\([^ |\t]*\)".*/\1/p' |sort|uniq| xargs -n1 -I {} printf "%60s {}\n"

    #sub manifests
    cat $1 | sed -n 's/.*include name="\(.*\)".*/\1/p' | \
    while read -r file; do
    if [ -n "${file}" ];then reppshow_manifesttree ${file} ${treedepth}; fi
    done
    (( treedepth=treedepth-3 ))
}



function reppmani(){
## ---------------------------------------------------------------------------
# read file and print line "include" keyword
# $1 manifest output file name
# $2 command
# $3 branch name or branch postfix
    local cmd=$1
    local opt=$2    
    local field=$3
    local name=$4

set -x
    case ${cmd}${opt} in
        help) cat <<- EOF
				ex) repp mani help
				ex) repp mani info
				ex) repp mani gen <outfile>      
				ex) repp mani create one <group|upstream|dest-branch|etc> <branch-name>
				ex) repp mani create each <group|upstream|dest-branch|etc> <branch-postfix>
EOF
    ;;      info)   bar inline "recently changed manifest file [default 10 commit]"
                    showRUN git log -10 --name-status --abbrev=6 --date=format:"%Y-%m-%d %H:%M" --pretty=format:"%C(yellow)%ad %C(red)%h %C(green)%s%C(reset)"
    ;;      gen)    bar inline "current manifest.xml regnerated with option"
                    clog "-r" "generate revision with [''| --suppress-dest-branch| --suppress-upstream-revision]"
                    clog "--json " "generate manifest to json format"
                    read -p "input option :" opt
                    showRUN repo manifest ${opt} -o ${REPP_PATH}/repp.xml
    ;;  createone)  bar inline "change manifest field with value"
                    echo "upstream " "<branch-name>"
                    clog "ex) group|upstream|dest-branch|etc " "<newname to be replaced>"
                    repo manifest | sed -E "s#${field}=\"(.*)\"#${field}=\"${name}\"#" 
    ;;  createeach) bar inline "change manifest field with value-postfix"
                    echo "upstream " "<branch-postfix>"
                    clog "ex) group|upstream|dest-branch|etc " "<postfix to be added>"
                    repo manifest | sed -E "s#${field}=\"(.*)\"#${field}=\"\1${name}\"#"

    ;; esac
    
set +x
}



function reppbranch(){
## ---------------------------------------------------------------------------
# read file and print line "include" keyword
# $1 manifest output file name
# $2 command
# $3 branch name or branch postfix
# todo: branch 생성/각각 생성, 제거, 생성(rev까지)확인
    local cmd=$1
    local opt=$2
    local name=$3

    case ${cmd}${opt} in
              help) cat <<- EOF
					ex) repp branch help
					ex) repp branch create one <branch-name>
					ex) repp branch create each <branch-postfix>
					ex) repp branch remove one <branch-name>
					ex) repp branch remove each <branch-postfix>
					ex) repp branch check  one <branch-name>
					ex) repp branch check  each <branch-postfix >
                    ex) repp branch checksum
EOF
    ;;   createone) showRUN repo forall -pc 'git push ${REPO_REMOTE} HEAD:refs/heads/${1}' ${name}
    ;;  createeach) showRUN repo forall -pc 'git push ${REPO_REMOTE} HEAD:refs/heads/${REPO_RREV}_${1}' ${name}
    ;;   removeone) showRUN repo forall -pc 'git push ${REPO_REMOTE} --delete ${1}' ${name}
    ;;  removeeach) showRUN repo forall -pc 'git push ${REPO_REMOTE} --delete ${REPO_RREV}_${1}' ${name}
    ;;        list) bar inline "show remote branches including ${name}" 
                    repo forall -pc 'git ls-remote -h ${REPO_REMOTE} refs/heads/*${1}*' ${name}
    ;;    checkone) bar inline "check exact ${name} remote branche is existed for all gits" 
                    repo forall -pc '[ -z "$(git ls-remote -h ${REPO_REMOTE} refs/heads/$1)" ] && echo not existed || echo existed' ${name}
    ;;   checkeach) bar inline "check "ending with ${name}" remote branche is existed for all gits" 
                    repo forall -pc '[ -z "$(git ls-remote -h ${REPO_REMOTE} refs/heads/${REPO_RREV}_$1)" ] && echo not existed || echo existed' ${name}
    ;;    checksum) 
                    bar inline "local HEAD md5sum in all repository"
                    showRUN repo forall -c 'git log -1 --pretty=format:%H' | md5sum
                
                    bar inline "remote HEAD md5sum in all repository tracked"
                    showRUN repo forall -c 'git ls-remote -h ${REPO_REMOTE} ${REPO_RREV}| cut -f1' |md5sum

                    bar inline "${name} md5sum in all repository tracked"
                    showRUN repo forall -c 'git ls-remote -h ${REPO_REMOTE} refs/heads/${REPO_RREV}_${name}| cut -f1' ${name} |md5sum        
                    
                    bar inline "shows diff between tags shortly"
                    #repo forall -pc 'git diff --shortstat tagA tagB'
    ;;           *) echo "usage) repp branch help"
    ;; esac
}



function gittbranch_list(){
## ---------------------------------------------------------------------------
# show branch local & remote
# $1 all or filter
    local filter

    ## list option must be wrapped with quoat ex) --list '*relese*'
    bar inline "branch local"
    echo "these branches are existed in local repository"
    clog "[local]" "could be synced by remote, if so, traced is marked"
    git branch -vv 

    ## prevent globbing
    set -o noglob
    bar inline "sort by recently updated branches by new commit"
    echo "branch: remote tracked with filter (${filter:-all}) top 20 in local repository"
    echo "this branches was downloaded when git fetch equivalent command is executed"
    clog "[not latest]" "could be latest by git pull"
    
    [ -z "${1}" ] && filter="" || filter="--list *${1}*"
    git branch -rvv --sort=-committerdate ${filter} | head -20
    
    bar inline "sort by recently created branches"
    echo "branch: remote all with filter (${filter:-all}) by date top 20 in remote repository"
    echo "this branches could be downloaded by git fetch command"
    clog "[always latest]" "read from remote live"
    warn "this command is not correct, please watch out"
    
    [ -z "${1}" ] && filter="*" || filter="*${1}*"
    showRUN git ls-remote -h ${GITT_REMOTE} refs/heads/${filter} --sort=-committerdate | head -20
    set +o noglob
}


function gittbranch(){
## ---------------------------------------------------------------------------
# read file and print line "include" keyword
# $1 command
# $2 branch name or branch postfix
    local cmd=$1
    local name=$2


    case $cmd in
       help) cat <<- EOF
				ex) gitt branch list <''|name-filter>
				ex) gitt branch create|new <name>
				ex) gitt branch delete|remove <name>
EOF
    ;; create|new)  if [ -z "${name}" ]; then err "branch name must be input" && return 1;fi
                showRUN git push ${GITT_REMOTE} HEAD:refs/heads/${name}
    ;; delete|remove)  if [ -z "${name}" ]; then err "branch name must be input" && return 1;fi
                showRUN git push ${GITT_REMOTE} --delete ${name}
    ;; list) gittbranch_list "${name}"
    ;; *) echo "usage) gitt branch help"
    ;; esac
}



function reppinfo(){
## ---------------------------------------------------------------------------
# print information of repo
# $1 manifests file (default is current manifests)
    pushd ${REPP_PATH} 
    oldIFS=${IFS}; IFS='';

    #show repo dir path
    bar inline "repo path"
    log "${REPP_PATH}"

    #get global variable and repo init command.
    reppget_repcmd info

    #show manifest file with included sub manifests.
    local manifest=${1:-${FILE_MANI}}
    bar inline "manifests"
    clog  "    <name of manifest>                                      <including branches>"
    reppshow_manifesttree ${manifest} 0

    #show count of repository
    ## block infomation
    bar inline "misc information for this repositories"
    clog "number of repositories: " $REPP_COUNT

    clog "md5 sum for all repositories:"
    repo forall -j16 -c git log -1 --pretty=format:%H | md5sum

    #show last synced time
    if [ -f .git/FETCH_HEAD ]; then clog "last manifest-synced date: " $(stat -c %y .git/FETCH_HEAD );
    else clog "last manifest-synced time(check date of files below): " $(ls -lct | tail -10);fi

    IFS=${oldIFS}
    popd
}



function reppshow(){
## ---------------------------------------------------------------------------
# print information(changes, recent commits) of current repository#
    #topic/working branch
    bar inline "repo branch: check if working branch existed (WAIT: It takes time) "
    repo branch

    #run command "repo info"
    bar outline "it takes time to get information..."
    bar inline "repo status: uncommitted changes list saved to [ repp.status ]"
    echo "repo status" > ${REPP_ROOT}/repp.status

    #remove colored output with 1) sed command, 2) --color option
    #repo status -j8 |sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" >> ${REPP_ROOT}/repp.status 
    repo --no-pager --color=never status -j8 >> ${REPP_ROOT}/repp.status 
    
    #list up repo commit, remote, branch, project, path
    reppfind |more -60

    #### repo info command is duplicated with reppfind functionality, so remove it.
    #bar inline "repo info: git repo/source path /branch rev saved to [ ${REPP_ROOT}/repp.status ]"
    #echo "repo info" >> ${REPP_ROOT}/repp.status
    #repo info |sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" >> ${REPP_ROOT}/repp.status 
}



function reppfind_recentcommit(){
## ---------------------------------------------------------------------------
# print information of repo
# $1 manifests file (default is current manifests)
    local count=$1
    local out

    #echo "[$1][$count][$out]"
    if [ -z $1 ]; then read -p "how many commit want to read? [#:number| enter:20| save:savefile| ctrl+c/q:exit]: " count; fi

    case $count in
        *[0-9]*) out='/dev/stdout';;
        '') out='/dev/stdout'
            count=20
            log "\nonly shows recent maxium 20 first-commits(git log -1) from all repository"
            ;;
        *)  out=${REPP_ROOT}/repp.commit
            count=${REPP_COUNT}
            log "\check file [$out], all -1 commits are saved"
            ;;
    esac

    echo "repo forall -c \"git log -1 --abbrev=6 --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%ad  %h  [%an] %d %s%n'\" |sort -r |head -${count:-50}"
    echo "> $out"

    bar outline "repo get recent commit"
    bar inline "date:YMD HMS]       [sha]   [author]      [commit title]                                            [git project                            branch"
    repo forall -j16 -c 'printf "%-100.100s %-80s \n" "$(git log -1 --abbrev=6 --date=format:"%Y-%m-%d %H:%M:%S" --pretty=format:"%ad  %h  [%an] %s")" "[${REPO_PROJECT}  ${REPO_RREV}]"' |sort -r |head -${count:-50} > $out
    #repo forall -c "git log -1 --abbrev=6 --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%ad  %h  [%an] %d %s%n'" |sort -r |head -${count:-50} > $out

}



function reppfind(){
## ---------------------------------------------------------------------------
# find git repository with path and project name with regexp
# $1 path or project
# usage: reppfind [path|project]
    bar inline "all repository info is save to repp.csv" > /dev/stderr
    file_log=${REPP_ROOT}/repp.csv
    repo forall -j1 -c 'printf "%.6s|%.7s|%-22.22s|%-74.74s|%.80s \n" "${REPO_LREV}" "${REPO_REMOTE}" "${REPO_RREV}" "${REPO_PROJECT}" "${REPO_PATH}"' \
     > $file_log
     
    case $1 in 
      comment) @로 시작하면 coloume을 출력
    ;; @rev)      echo "REPO_LREV";    awk -v FS="|" '{print $1}' $file_log 
    ;; @remote)   echo "REPO_REMOTE";  awk -v FS="|" '{print $2}' $file_log |sort |uniq
    ;; @branch)   echo "REPO_RREV";    awk -v FS="|" '{print $3}' $file_log |sort |uniq
    ;; @git)      echo "REPO_PROJECT"; awk -v FS="|" '{print $4}' $file_log |sort 
    ;; @path)     echo "REPO_PATH" > /dev/stderr;   awk -v FS="|" '{print $5}' $file_log |sort 
    ;; "")        printf "\e[1;33m%6.6s %7.7s %-22.22s %-74.74s %.80s \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
                  cat $file_log | tee  >(wc -l) 
    ;; *)         printf "\e[1;33m%6.6s %7.7s %-22.22s %-74.74s %.80s \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
                  cat $file_log | grep -i --color=always $1
    ;;
    esac
}



function reppcheck_version(){
## ---------------------------------------------------------------------------
# print information of repo
# $1 manifests file (default is current manifests)
    echo "this version is expected to used, please check this version is matched to your local version"

    bar inline "expected"
    info "warning: this is the repo packaged with this project."
    $REPP_PATH/../repo/repo version

    printf "\n\n"
    bar inline "found"
    info "the local version currently you are using"
    bar inline "what"
    repo --version

    echo
    py_path=$(which python) >/dev/null
    py_ver="$(python --version 2>&1)"
    printf "[check] %s is working in [%s]\n" "${py_ver}" "${py_path}"

    bar inline "where"
    which repo
    which git
    
    local VER=$(repo --version | grep "repo version"  |tr -dc '[:digit:]')
    if (( ${VER:0:3} < 230 )); then 
        under "you need to upgrade 'repo' to use full functionality" "\n"
		clog "1. remove old .repo:" rm -rf ${REPP_ROOT}/.repo
		clog "2. download to dir:" git clone https://gerrit.googlesource.com/git-repo ${path_mirror}/repo2 --mirror
		clog "3. replace repo and repo init:" [--repo-url=${REPP_URL}] --\> [${path_mirror}/repo2]
        pushd ${REPP_PATH} ; reppget_repcmd info ; popd
		clog "-->" 
        echo "${REPP_CMD/${REPP_URL}/${path_mirror}/repo2}"
        #| sed -e 's#--repo-url=${REPP_URL}#--repo-url=${path_mirror}/repo2'
    fi
}



function reppcheck_serverdelay(){
## ---------------------------------------------------------------------------
# find replication server
# $1 server-url
# $2 port-number
    local server_port=${REPP_REMOTE#*@}
    local server=${1:-${server_port%:*}}
    local port=${2:-$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')}

    ping $server -s 1016 -c 4 -A
    printf "${yellow}--------------------------------------------------------------------------------------\n${NCOL}"
    if [ $? -ne 0 ]; then continue; fi
    ssh $server -p $port -o ConnectTimeout=2 -o ConnectionAttempts=1 gerrit show-caches
    if [ $? -ne 0 ]; then continue;fi
    printf "${yellow}--------------------------------------------------------------------------------------\n${NCOL}"
    echo "please check 1) ipg/ewma from ping, 2) AvgGet from gerrit connection"
}



function reppcheck_connection(){
## ---------------------------------------------------------------------------
# check connection and report error
# $1 server
# $2 port
# $3 password
    local server_port=${REPP_REMOTE#*@}
    local server=${1:-${server_port%:*}}
    local port=${2:-$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')}
    local manifest=${3:-${server_port#*/}}
    local branch=${4:-${REPP_BRANCH}}
    local ret


    #local port=$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')
    bar inline "step1: check if ssh is installed"
    if [ -x "$(command -v ssh)" ]; then  log "ssh is installed in [$(which ssh)]"; else err "ssh is not installed"; fi

    if [ -z $server ] || [ -z $port ];then warn "usage) repp check vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
    bar inline "step2: check if server tcp port is well listened"
    timeout 5 bash -c "</dev/tcp/$server/$port"
    if [ $? == 0 ];then echo "server $server over port $port is listened"
    else echo "server $server over port $port is not listened"; fi

    bar inline "step3: check if sshd is serviced on this port $port"
    reppcheck_sshconnection $server $port

    bar inline "step4: check if gerrit service is valid"
    reppcheck_gerritconnection ssh $server -p $port gerrit version

    if [ -z $manifest ];then warn "usage) repp check vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
    bar inline "step5: check if I can access git (default: manifest)"
    ret=$(ssh $server -p $port gerrit ls-projects --prefix ${manifest} -b ${branch})

    echo "can accessed [${ret#* }]"
    set +x

}



function reppmenu(){
## ---------------------------------------------------------------------------
# show ui menu for this script
MENU_REPP=(
"info: shows repository info such as manifest path, repo cmd, tree of manifests, etc
    ex) repp info, repp info default.xml, repp info event/manifest.xml"
"show: shows uncommited changes, top -1 commits, md5 sum, repo info for all repositories
    ex) repp show, repp show|more, repp show| grep build, cat repp.status"
"go: move path to repo root dir, manifest dir, git path nearby with similar depth.
    ex) repp go (selcetion menu popup)"
"commit: shows lastest commits(git log -1) from all repository (default 20)
    ex) repp commit, repp commit 4, repp commit log.txt(save as)"
"find: (list) search string in all [repo path] : [repo revision] : [repo name]
    ex) repp find, repp list|more, repp find build, repp list|grep -v build
    ex) repp find @rev [@rep| @remote| @branch| @git| @path)"
"init: repo init with automatic options
    ex) repp init -u ssh://${USER:+${USER}@}vgit.lge.com:29420/linux/manifest.git -b mib3_release
    ex) repp init -b lampauto_s_release -m all.xml
    ex) repp init -b lampauto_r_release -m lampauto/lampauto-gm-recent.xml
    ex) repp init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1"
"sync: repo sync with optimized multi-job and options
    ex) repp sync, repp sync 8, repp sync 16 --force-sync(more options)"
"reset: reset all repositories to original state
    in case) use this, when repository has dirty commits."
"server: check delay from server or confirm the server status
    ex) repp server, repp server lamp.lge.com 29418"
"check: find accessibility for manifest git or normal git
    ex) repp check, repp check vgit.lge.com 29420 tiger/tools tiger_release
                   repp check [git-server] [port] [project]  [branch]"
"version: shows repo/git/python version info used in current repo"    
)


printf ${green}
cat << PREFACE
==============================================================
 welcome to repp & gitt
 -------------------------------------------------------------
 command usage: ex) repp, repp info, repp show [default.xml]
 command usage: ex) gitt, gitt info, gitt show [currnet git]
 ex) repp find [string], repp sync 16 --force-sync, etc
 help: http://collab.lge.com/main/x/wY6wa
==============================================================
PREFACE
printf ${NCOL}

local COLUMNS=60
PS3=$'\e[00;35m=== Please input command! [enter:menu, number:choice, ctrl+c:exit] === : \e[0m'
select CHOICE in "${MENU_REPP[@]}"; do
    repp "${CHOICE%%:*}";
    if [ -n "$?" ]; then return 1;fi
done
}



function gittmenu(){
## ---------------------------------------------------------------------------
# main handler for this scriptre
# $1 command
MENU_GITT=(
"info: shows git path, gerrit info/url/remote, push command, commit info, sync time.
    ex) gitt info"
"show: shows git (default 15) commits history, diff history
    ex) gitt show, gitt show 20 --all"
"go: move to current .git path
    ex) gitt go"
"reset: clean with 'git reset --hard  && git clean -xdf'
    ex) gitt reset"
"find: branch, commit(author, rev, commit msg)
    ex) repp find, repp list|more, repp find build, repp list|grep -v build
    ex) repp find @rev [@rep| @remote| @branch| @git| @path)"
)


printf ${green}
cat << PREFACE
==============================================================
 welcome to gitt & repp
 -------------------------------------------------------------
 command usage: ex) gitt, gitt info, gitt show [currnet git]
 command usage: ex) repp, repp info, repp show [default.xml] 
 ex) gitt find [string], gitt show, etc
 help: http://collab.lge.com/main/x/wY6wa
==============================================================
PREFACE
printf ${NCOL}

local COLUMNS=60
PS3=$'\e[00;35m=== Please input command! [enter:menu, number:choice, ctrl+c:exit] === : \e[0m'
select CHOICE in "${MENU_GITT[@]}"; do
    gitt "${CHOICE%%:*}";
    if [ -n "$?" ]; then return 1;fi
done
}

##oneline function
gittcheck_isgitproject(){ git -C "$1" rev-parse --is-inside-work-tree &> /dev/null ;}

function gittcheck_gitpath(){
## ---------------------------------------------------------------------------
    #readarray -t GITT_REMOTE < <(git remote -v |cut -f1|uniq)
    GITT_REMOTE=$(git remote|head -1) 
    
    #git config --get-regexp remote.$GITT_REMOTE |sort|grep -Ee "(projectname|review|url)"
    GITT_PROJECT=$(git config --get-regexp remote.*.projectname|cut -d' ' -f2)
    GITT_BRANCH=$(git branch -ar |grep -e '->' |sed -E 's#.*[/|>](.*)$#\1#')    
    GITT_REVIEW=$(git config --get-regexp remote.*.review|cut -d' ' -f2)
    GITT_URL=$(git config --get-regexp remote.${GITT_REMOTE}.url|cut -d' ' -f2)
    GITT_PATH=$(git rev-parse --show-toplevel)
    if [ "$1" = "print_y" ]; then echo "${GITT_PATH}"; fi
}


function gittinfo(){
## ---------------------------------------------------------------------------
# main handler for this scriptre
# TODO: clone command
    local TEMP
    under "git info"
    bar inline "git path"
    if ! gittcheck_gitpath print_y ;then echo "we are not in git project" && return 1; fi
    
    ## "error: must check" must be checked!!!
    bar inline "show all remote info"    
    clog ' remote:' ${GITT_REMOTE:="error: must check"}
    clog 'project:' ${GITT_PROJECT:="not defined"}
    clog ' branch:' ${GITT_BRANCH:="error: must check"}    
    clog ' review:' ${GITT_REVIEW:="not defined"}
    clog '    url:' ${GITT_URL:="error: must check"}

    #review system check
    case $(git config --get-regexp remote|cut -d' ' -f2) in
      help)             echo "site customization"
	;;*github.com*)     GIT_SITE=$(printf "https://%s" ${GITT_URL}|sed -E 's#^.*github.com:(.*.git)$#http://github.com/\1#')
	;;*lge.com*manifest.git*) case ${GITT_URL} in 
                              *vgit.lge.com:29420*) GIT_SITE=$(printf "http://vgit.lge.com/%s/%s" 'na' admin/repos/${GITT_URL##*0/} ) ;;
                              *vgit.lge.com:29430*) GIT_SITE=$(printf "http://vgit.lge.com/%s/%s" 'eu' admin/repos/${GITT_URL##*0/} ) ;;
                              *vgit.lge.com:29440*) GIT_SITE=$(printf "http://vgit.lge.com/%s/%s" 'as' admin/repos/${GITT_URL##*0/} ) ;;
                              *vgit.lge.com:29550*) GIT_SITE=$(printf "http://vgit.lge.com/%s/%s" 'adas' admin/repos/${GITT_URL##*0/} ) ;;
                              *vgit.lge.com:29999*) GIT_SITE=$(printf "http://vgit.lge.com/%s/%s" 'devops_test' admin/repos/${GITT_URL##*0/} ) ;;
                              *) GIT_SITE="please add site custom setting" ;;
                              esac
	;;''|*)             GIT_SITE=$(printf "%s/admin/repos/%s" $(echo ${GITT_REVIEW}|sed -E 's#(.*)[/]$#\1#') ${GITT_PROJECT} )
    ;;esac
    clog "review system site:" ${GIT_SITE}
    
    bar inline "git push commands"
    TEMP=$(printf "git push $GITT_REMOTE HEAD:refs/heads/%s" ${GITT_BRANCH})    
    clog " git push direct:" $TEMP
    clog " git push review:" ${TEMP/\/heads/\/for}    
    
    bar inline "recent commit info"
    git show --stat --oneline HEAD
    
    bar inline "last synced time"
    #show last synced time
    oldIFS=${IFS}; IFS='';
    if [ -f ${GITT_PATH}/.git/FETCH_HEAD ]; then clog "last manifest-synced date: " $(stat -c %y ${GITT_PATH}/.git/FETCH_HEAD );
    else clog "last manifest-synced date(check date of files below): " $(ls -lct ${GITT_PATH}/.git| tail -5);fi
    IFS=${oldIFS}

    under "branch info" 
    gittbranch list
}



function gittshow(){
## ---------------------------------------------------------------------------
# print information(commit info) of current repository#
# $1: number of commit
# $2: other option such as --all (all branch)    
    #topic/working branch
    bar outline "gitt show is based on command: git log "    
    bar inline "git commit history with option (to see all branche, gitt show 20 --all)"
    git log --decorate --graph -n${2:-15} --pretty=format:'%Cred%h -%C(yellow)%s %Cgreen(%ci) %C(blue)<%an>%Creset' $1

    bar inline "git commit diff history"
    echo "--since(=after), --before(=until)"
    echo "6 hour, 2-day, 2-week, 1-month, 1-year"
    clog "ex:" "--since=2-weeks, --since=04:24, --before=6-hours, --after=2022-11-10 --before=2022-11-20-23"
    read -p "input add option [enter(default):--pretty="short" --name-only | input option with default]" 
    
    git log --pretty="short" --name-only ${reply} |more -60
}



function gittreset(){
## ---------------------------------------------------------------------------
# reset git repositories
# $1 target

    case $1 in
      all)  repo forall -cj${NJOBS} 'git reset --hard ; git clean -xdf'
            echo "reset all repositories" ;;
      ''|*) if gittcheck_isgitproject; then 
                
                showRUN git reset --hard; showRUN git clean -xdf
            else 
                warn "this is not a git directory"; 
            fi  ;;
    esac
}



function gittfind(){
## ---------------------------------------------------------------------------
# print information(commit info) of current repository#
# $1: number of commit
# $2: other option such as --all (all branch)    
    bar outline "search in commit with regexp(\$1) in files(\$2)"    

    under "git log --committer=\"$1\""
    clog 'committer history' "ex) git log --committer='.*joongkeun' "    
    git log --committer="$1"

    under "git log -i --grep=\"$1\" " 
    clog 'commit message history' "ex) git log -i --grep='.*debugprint' " 
    git log -i --grep="$1"
    
    under "git log -i -G\"$1\" ${@:2}" 
    clog 'commit contents history' "ex) git log -i -G'.*debugprint' zlib.c" 
    git log -i -G"$1" "${@:2}"

    under "git grep -n \"$1\" ${@:2}" 
    clog 'current files tracked in git' "ex) git grep -n '.*debugprint' *.c" 
    git grep -n "$1" "${@:2}"

    under "git log -L :\"$1\":${@:2} " 
    clog 'function in git history' "ex) git log -L :func_debugprint:zlib.c"
    git log -L :"$1":"${@:2}"
}



function gitt(){
## ---------------------------------------------------------------------------
# main handler for this scriptre
# $1 command
local ret=0
if ! gittcheck_gitpath print_n;then err "we are not in git project" && return 1; fi

case "$1" in
    #$1:below ${@:2}:parameters
    info)       gittinfo ;;
    show)       gittshow "${@:2}";;
    go)         cd "$(gittcheck_gitpath print_y)" ;;
    reset)      gittreset "${@:2}";;
    find)       gittfind "${@:2}";;
    branch)     gittbranch "${@:2}";;
    debug)      gittdebug "${@:2}";;
    '')         gittmenu "${@:2}";;
    *)          git "${@}";;    
esac    
return $ret
}




function repp(){
## ---------------------------------------------------------------------------
# main handler for this scriptre
# $1 command
local ret=0
case "$1" in
    #$1:below ${@:2}:parameters
    info)       reppcheck_precondition print_y || return 1
                reppinfo  "${@:2}";;
    show)       reppcheck_precondition print_y || return 1
                #reppinfo "${@:2}"  2>&1 | tee ${REPP_ROOT}/repp.status
                reppshow "${@:2}"  2>&1 
                info "please check file [${REPP_ROOT}/repp.status]"
                warn "you can use this file to compare other repo.";;                
    go)         reppcheck_precondition print_y || return 1
                local menu_items=('go ROOT　dir' 'go Manifests　dir' 'go GIT　root dir' 'exit')
                run_menu "${menu_items[@]}"
                case "$?" in
                    1|11)  cd "${REPP_ROOT}"        ;;
                    2|12)  cd "${REPP_PATH}"        ;;
                    3|13)  reppgo .git              ;;
                    *)  echo 'exit) stay here'      ;;
                esac;;
    commit)     reppcheck_precondition print_y || return 1
                reppfind_recentcommit "${@:2}";;
    find|list)  reppcheck_precondition print_y || return 1
                reppfind "${@:2}";;
    branch)     reppcheck_precondition print_y || return 1
                reppbranch "${@:2}";;
    mani)       reppcheck_precondition print_y || return 1
                reppmani "${@:2}";;                
    init)       reppinit "${@:2}"
                if [ $? -eq 0 ]; then
                    info "To RUN next command:"
                    reppfind_syncerror
                fi;;
    sync)       reppcheck_precondition print_y || return 1
                reppfind_syncerror "${@:2}";;
    reset)      reppcheck_precondition print_y || return 1
                gittreset all ;;

    version)    reppcheck_precondition print_y || return 1
                reppcheck_version "${@:2}";;
    check)      reppcheck_precondition print_n || return 1
                reppcheck_connection "${@:2}";;
    server)     reppcheck_precondition print_n || return 1
                reppcheck_serverdelay "${@:2}";;
    '') 
                reppmenu "${@:2}";;
    *) 
                repo "${@}";;
esac
return $ret
}



function reppcheck_precondition(){
## ---------------------------------------------------------------------------
# pre-check
# $1 command
    #find & move manifest dir
    local ret=1

    reppfind_repodir .repo/manifests 5 print_n
    if [ -d "${REPP_PATH}" ];then 
        pushd ${REPP_PATH}; REPP_ROOT=${REPP_PATH%/.repo*}
            #set global variable
        REPP_REMOTE=$(git remote -v |grep fetch |awk '{print $2}')
        REPP_BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name @{u}| sed 's:.*/::')
        REPP_URL=$(cat ../repo/.git/config |grep url|sed 's/.*= \(.*\)/\1/')
        REPP_MIRROR=$(cat ../manifests.git/config |grep reference|sed 's/.*= \(.*\)/\1/')
        REPP_COUNT=$($REPP_PATH/../repo/repo list |wc -l)
        
        popd
        ret=0
    fi

    if [[ $ret -eq 1 && "$1" = "print_y" ]]; then 
        printf "%s\n" ${REPP_PATH_ALL[@]};
        bar inline "WARNING"
        err "you are not in repo project, please check !";      
    fi
    return $ret
}



function gittdebug(){
#reppdebug & gittdebug
#repo forall -c 'echo ${REPO_REMOTE}:${REPO_PROJECT}:${REPO_PATH}:${REPO_LREV}:${REPO_RREV}'
    reppcheck_precondition print_n
    local file_log=$(mktemp)
    cat <<\EOL > ${file_log}
        bar inline "GITT_VARIABLE && REPP_VARIABLE"
        for var in \
        '${GITT_REMOTE}' '${GITT_PROJECT}' '${GITT_BRANCH}' '${GITT_REVIEW}' '${GITT_URL}' '${GITT_PATH}' \
        '${REPP_PATH}' '${REPP_ROOT}' '${REPP_REMOTE}' '${REPP_BRANCH}' '${REPP_URL}' '${REPP_MIRROR}' '${REPP_COUNT}'
        do 
           dlog $var $(eval echo $var)
        done
        
        bar inline "[${GITT_PROJECT}] print repo variable"
        showRUN repo forall ${GITT_PROJECT} -c 'echo ${REPO_REMOTE}\| ${REPO_PROJECT}\| ${REPO_PATH}\| ${REPO_LREV}\| ${REPO_RREV}'
        
        bar inline "[all repo] print repo variable"
        dlog '${REPO_PROJECT}| ${REPO_REMOTE}| ${REPO_PATH}| ${REPO_RREV}| ${REPO_LREV}| ${REPO_OUTERPATH}| ${REPO_INNERPATH}| ${REPO_COUNT}'
        repo forall -c 'echo ${REPO_PROJECT}\| ${REPO_REMOTE}\| ${REPO_PATH}\| ${REPO_RREV}\| ${REPO_LREV}\| ${REPO_OUTERPATH}\| ${REPO_INNERPATH}\| ${REPO_COUNT}' | more -60
EOL

    ##run echo 
    source ${file_log}
}



##============================================================================
## Main
##============================================================================
GITT_REMOTE= &&GITT_PROJECT= &&GITT_BRANCH= &&GITT_REVIEW= &&GITT_URL= &&GITT_PATH=
REPP_PATH= &&REPP_ROOT= &&REPP_REMOTE= &&REPP_BRANCH= &&REPP_URL= &&REPP_MIRROR= &&REPP_COUNT= &&REPP_CMD=
REPP_PATH_ALL=()

(return 0 2>/dev/null) && sourced=1 || sourced=0
if [ $sourced -eq 0 ]; then repp $@;
else  #if sourced 
    echo "[WELCOME] repp utility is applied for current shell" 
    #hide local function, need to implements
fi

